-- MySQL Script generated by MySQL Workbench
-- недеља, 26. фебруар 2017. 19:56:43 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema twitter_log
-- -----------------------------------------------------
-- Database which contains downloaded tweets (some selected data related to a tweet) and some data of related user.

-- -----------------------------------------------------
-- Schema twitter_log
--
-- Database which contains downloaded tweets (some selected data related to a tweet) and some data of related user.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `twitter_log` DEFAULT CHARACTER SET utf8 ;
USE `twitter_log` ;

-- -----------------------------------------------------
-- Table `twitter_log`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_log`.`user` ;

CREATE TABLE IF NOT EXISTS `twitter_log`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_str` VARCHAR(50) NOT NULL DEFAULT 0,
  `name` VARCHAR(100) NOT NULL,
  `profile_image_url` TEXT NULL,
  `location` VARCHAR(100) NULL,
  `url` TEXT NULL,
  `screen_name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_str_UNIQUE` (`id_str` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `twitter_log`.`tweet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitter_log`.`tweet` ;

CREATE TABLE IF NOT EXISTS `twitter_log`.`tweet` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_str` VARCHAR(50) NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL DEFAULT NULL,
  `favorited` VARCHAR(10) NULL DEFAULT NULL,
  `retweet_count` VARCHAR(10) NULL DEFAULT NULL,
  `user_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `text` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_str_UNIQUE` (`id_str` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `twitter_log`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

